# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='action',
            field=models.CharField(default='buy', max_length=10),
        ),
    ]
