# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_item_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublist',
            name='sub_list',
        ),
        migrations.AddField(
            model_name='sublist',
            name='sub_list',
            field=models.ManyToManyField(to='mylist.Checklist'),
        ),
    ]
