# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_auto_20160320_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shoplist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mylist.Checklist'),
        ),
    ]
