# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0008_auto_20160327_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='sub_list',
            field=models.ManyToManyField(related_name='chklists', to='mylist.Checklist'),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='sub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
